---
name: Term-Menus
version: 1.12
author:
  - Brian Kelly <Brian.Kelly@fullautosoftware.net>
abstract: 'Create Powerful Terminal, Console and CMD Enviroment Menus'
license: gpl
requires:
  perl: 5.002
provides:
  Term::Menus:
    file: lib/Term/Menus.pm
    version: 1.12
generated_by: Module::Build version 0.261
