---
abstract: 'Create Powerful Terminal, Console and CMD Enviroment Menus'
author:
  - 'Brian M. Kelly <Brian.Kelly@fullautosoftware.net>'
configure_requires:
generated_by:
license: gpl-3.0
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-Menus
provides:
  Term::Menus:
    file: lib/Term/Menus.pm
    version: 2.79
  TMMemHandle:
    file: lib/Term/Menus.pm
requires:
  Data::Dump::Streamer: 0
  Devel::Symdump: 0
  PadWalker: 0
  Term::ReadKey: 0
  Term::RawInput: 1.20
resources:
  license: http://www.gnu.org/licenses/agpl.html 
version: 2.79
