---
abstract: "Create Powerful Terminal, Console and CMD Enviroment Menus\r"
author:
  - "Brian M. Kelly <Brian.Kelly@fullautosoftware.net>\r"
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-Menus
provides:
  Term::Menus:
    file: lib/Term/Menus.pm
    version: 1.40
requires:
  Term::ReadKey: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 1.40
